fix build erros
DgnClientSdk was failing for two days because of this

********************************************************************************
Error(s) for c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:
********************************************************************************
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:75:18: error: cannot pass object of non-trivial type 'BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:2776:18: error: cannot pass object of non-trivial type 'const BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:2798:18: error: cannot pass object of non-trivial type 'const BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:2820:18: error: cannot pass object of non-trivial type 'const BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:2845:18: error: cannot pass object of non-trivial type 'const BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:3006:18: error: cannot pass object of non-trivial type 'BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]
c:/build/src/mds06t/WSClient/Tests/UnitTests/Published/WebServices/Client/WSRepositoryClientTests.cpp:3046:18: error: cannot pass object of non-trivial type 'BentleyB0200::Utf8String' through variadic constructor; call will abort at runtime [-Wnon-pod-varargs]