EF: PRG builds fail because .../Output/WinRTx86/BuildContexts/DgnClientFx/Delivery/DgnClientSdkIncludeDirectory/folly/detail/ThreadLocalDetail.h(347): error C2483: 'threadEntrySingleton': object with destructor or non-aggregate type cannot be declared with thread storage duration in WinRT code I cannot reproduce locally, and quite frankly ThreadEntry has no constructor, no destructor, and is made of purely POD member types. We already don't define FOLLY_TLD_USE_FOLLY_TLS on __apple__ though, so giving it a try here.