fix android error
DgnPlatform/DgnCore/RepositoryManager.cpp:245:65: error: conditional expression
is ambiguous; 'RefCountedPtr<BentleyB0200::Dgn::IBriefcaseManager>' can be
converted to 'RefCountedPtr<BulkUpdateBriefcaseManager>' and vice versa