Remove ChangeManager.h from use of public API - forward declared WebServices::FileInfo conflicts with iModelHub::FileInfo
\WebServices/iModelHub/Client/FileInfo.h(47): error C2248: 'BentleyB0200::iModel::Hub::BaseFileInfo::BaseFileInfo': cannot access private member declared in class 'BentleyB0200::iModel::Hub::BaseFileInfo'
\WebServices/iModelHub/Client/BaseFileInfo.h(38): note: see declaration of 'BentleyB0200::iModel::Hub::BaseFileInfo::BaseFileInfo'
\WebServices/iModelHub/Client/BaseFileInfo.h(22): note: see declaration of 'BentleyB0200::iModel::Hub::BaseFileInfo'
\WebServices/iModelHub/Client/FileInfo.h(48): error C2248: 'BentleyB0200::iModel::Hub::BaseFileInfo::BaseFileInfo': cannot access private member declared in class 'BentleyB0200::iModel::Hub::BaseFileInfo'
\WebServices/iModelHub/Client/BaseFileInfo.h(39): note: see declaration of 'BentleyB0200::iModel::Hub::BaseFileInfo::BaseFileInfo'
\WebServices/iModelHub/Client/BaseFileInfo.h(22): note: see declaration of 'BentleyB0200::iModel::Hub::BaseFileInfo'

BaseFileInfo.h picks up WebServices::FileInfo (from ChangeManager.h) based on
include order.

Add include into test case to try ensure such conflicts do not occur again

SRB:Andrius.Zonys